apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-app
  namespace: retail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-app
  template:
    metadata:
      labels:
        app: retail-app
    spec:
      containers:
        - name: retail-app
          image: crudapp:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: retail-app-svc
  namespace: retail
spec:
  selector:
    app: retail-app
  ports:
    - name: http
      port: 80
      targetPort: 8081
  type: NodePort
