apiVersion: v1
kind: Service
metadata:
  name: retail-app-svc
  namespace: retail
spec:
  selector:
    app: retail-app
  ports:
    - protocol: TCP
      port: 80          # Service Port
      targetPort: 8081  # Container Port
  type: ClusterIP
