param(
    [int]`$ConcurrentUsers = 5,
    [int]`$Duration = 120,
    [string]`$Namespace = "retail"
)

Write-Host "🚀 Starting load test with `$ConcurrentUsers users for `$Duration seconds..." -ForegroundColor Green

`$testName = "load-test-" + (Get-Date -Format "yyyyMMddHHmmss")

`$yamlContent = @"
apiVersion: v1
kind: Pod
metadata:
  name: `$testName
  namespace: `$Namespace
spec:
  containers:
  - name: load-generator
    image: curlimages/curl:latest
    command:
    - /bin/sh
    - -c
    - |
      echo 'Load test started...'
      end_time=\`$((\`$(date +%s) + `$Duration))
      request_count=0

      while [ \`$(date +%s) -lt \`$end_time ]; do
        case \`$((\`$request_count % 10)) in
          0|1|2|3|4) 
            curl -s http://retail-app-internal:8081/api/products > /dev/null ;;
          5|6) 
            curl -s -X POST http://retail-app-internal:8081/api/products \
              -H 'Content-Type: application/json' \
              -d '{\"name\":\"LoadTest\`$(date +%s)\",\"description\":\"Generated by load test\",\"price\":99.99}' > /dev/null ;;
          7|8|9) 
            curl -s http://retail-app-internal:8081/api/products/\`$((\`$RANDOM % 20 + 1)) > /dev/null ;;
        esac
        
        request_count=\`$((\`$request_count + 1))
        
        if [ \`$((\`$request_count % 50)) -eq 0 ]; then
          echo \"Sent \`$request_count requests...\"
        fi
        
        sleep 0.5
      done

      echo \"✅ Load test completed. Total requests: \`$request_count\"
  restartPolicy: Never
"@

`$yamlContent | kubectl apply -f -

Write-Host "📊 Monitoring load test progress..." -ForegroundColor Blue
kubectl logs -f `$testName -n `$Namespace

# Cleanup
Start-Sleep -Seconds 5
kubectl delete pod `$testName -n `$Namespace --ignore-not-found=true

Write-Host "✅ Load test completed!" -ForegroundColor Green