apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: retail
  labels:
    app: mongodb
    tier: database
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017
  # This service is only accessible within the cluster
  # Connection string: mongodb://username:password@mongodb-service:27017