apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: retail
  labels:
    app: mongo-express
    tier: frontend
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
    # For NodePort access (if LoadBalancer not available):
    # nodePort: 30081
  
  # If using minikube, access via: minikube service mongo-express-service -n retail
  # If using LoadBalancer, external IP will be assigned